name: 学生助理考勤

on:
  schedule:
    - cron: '30 5,23 * * *'

jobs:
  attendance:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Attendance
        run: python attendance.py -U ${{ secrets.USERNAME }} -P ${{ secrets.PASSWORD }} ${{ secrets.SERVER_KEY }}
